version: "3"

services:
  api:
    image: iron/functions:latest
    volumes:
      - "./api/data:/app/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - backend
    hostname:   functions-api
    privileged: true
    restart: always
  ui:
    image: iron/functions-ui:latest
    networks:
      - backend
    hostname:   ui
    privileged: true
    environment:
      NO_PROXY: "api:8080"         # should override to your.function.host:port
      API_URL:  "http://api:8080/" # should override to http://your.function.host:port/
    depends_on:
      - api
    restart: always
  proxy:
    image: lkwg82/h2o-http2-server
    ports:
      - "80:80"
    volumes:
      - "./proxy/etc:/etc/h2o"
      - "./proxy/log:/var/log/h2o"
    networks:
      - backend
    hostname: proxy
    working_dir: /etc/h2o
    restart: always

networks:
  backend:
