version: "3"

services:
  api:
    image: iron/functions:0.2.22
    ports:
      - "8080:8080"
    volumes:
      - "./api/data:/app/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - backend
    hostname:   functions-api
    privileged: true
    restart: always
  ui:
    image: iron/functions-ui:latest
    ports:
      - "4000:4000"
    networks:
      - backend
    hostname:   ui
    privileged: true
    environment:
      NO_PROXY: "api:8080"
      API_URL:  "http://api:8080/"
    depends_on:
      - api
    restart: always
  proxy:
    image: lkwg82/h2o-http2-server
    ports:
      - "80:80"
    volumes:
      - "./proxy/etc:/etc/h2o"
      - "./proxy/log:/var/log/h2o"
    networks:
      - backend
    hostname: proxy
    working_dir: /etc/h2o
    restart: always

networks:
  backend:
